name: lockfile-assay
on:
  pull_request_target:
jobs:
  assay:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: jsalvata/lockfile-assay@v1.0.2
